application: keteprojectq32015
version: 3
runtime: php55
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /
  script: pages/index.html

- url: /details
  script: pages/detail.html

- url: /about
  script: pages/about.html

- url: /focus
  script: pages/focus.html

- url: /apply
  script: pages/apply.html

- url: /contact
  script: pages/contact.html

- url: /slide
  script: pages/sld.html

- url: /asset/handshake.jpg
  script: assets/handshake.jpg

- url: /asset/zoomkids.jpg
  script: assets/zoomkids.jpg

- url: /asset/apply.jpg
  script: assets/apply.jpg

- url: /style
  static_dir: style/

- url: /bootstrap/css/
  static_dir: bootstrap/css/

- url: /bootstrap/js/
  static_dir: bootstrap/js/

- url: /assets
  static_dir: assets/

- url: /parts
  static_dir: parts/

# Serve images as static resources.
- url: /(.+\.(gif|png|jpg))$
  static_files: \1
  upload: .+\.(gif|png|jpg)$
  application_readable: true
